package: spectralDNS

user: spectralDNS

platform:
  - linux-64

engine:
  - python=2.7

install:
  - conda config --set always_yes true
  - conda config --add channels mikaem
  - conda build conf/conda
